import { useState } from "react"
import { LineChart, Line, XAxis, YAxis, Tooltip, Legend, ResponsiveContainer, BarChart, Bar, Cell } from "recharts"
const C = { bg1:"#0d1117",bg2:"#161b22",bg3:"#21262d",border:"#30363d",text1:"#e6edf3",text2:"#8b949e",green:"#3fb950",greenDim:"#3fb95020",red:"#f85149",redDim:"#f8514920",amber:"#d29922",blue:"#4d9cf5" }
const LIGAS = ["Premier League","La Liga","Serie A","Bundesliga"]
function StatCard({label,value,sub,color}){return(<div style={{background:C.bg3,border:`1px solid ${C.border}`,borderRadius:6,padding:"14px 18px",flex:1,minWidth:140}}><div style={{fontSize:11,color:C.text2,fontFamily:"'JetBrains Mono',monospace",letterSpacing:".08em",textTransform:"uppercase",marginBottom:6}}>{label}</div><div style={{fontSize:22,fontWeight:700,color:color||C.text1}}>{value}</div>{sub&&<div style={{fontSize:11,color:C.text2,marginTop:3}}>{sub}</div>}</div>)}
export default function BacktestPanel(){
const [liga,setLiga]=useState("Premier League")
const [bankroll,setBankroll]=useState(1000)
const [minEdge,setMinEdge]=useState(5)
const [data,setData]=useState(null)
const [loading,setLoading]=useState(false)
const [error,setError]=useState(null)
async function runBacktest(){setLoading(true);setError(null);setData(null);try{const res=await fetch(`/api/backtest?league=${encodeURIComponent(liga)}&bankroll=${bankroll}&min_edge=${minEdge/100}`);const json=await res.json();if(json.error)throw new Error(json.error);setData(json)}catch(e){setError(e.message)}finally{setLoading(false)}}
const chartData=data?data.chart_kelly.map((v,i)=>({n:i+1,Kelly:v,Plana:data.chart_flat[i]??null})):[]
const barData=data?Object.entries(data.accuracy_by_type).map(([k,v])=>({tipo:k,pct:v})):[]
return(<div style={{padding:20,display:"flex",flexDirection:"column",gap:16}}>
<div style={{background:C.bg2,border:`1px solid ${C.border}`,borderRadius:6,padding:16,display:"flex",gap:16,flexWrap:"wrap",alignItems:"flex-end"}}>
<div style={{display:"flex",flexDirection:"column",gap:6}}><label style={{fontSize:11,color:C.text2,fontFamily:"'JetBrains Mono',monospace",letterSpacing:".08em"}}>LIGA</label><select value={liga} onChange={e=>setLiga(e.target.value)} style={{background:C.bg3,border:`1px solid ${C.border}`,color:C.text1,borderRadius:4,padding:"6px 10px",fontSize:13}}>{LIGAS.map(l=><option key={l}>{l}</option>)}</select></div>
<div style={{display:"flex",flexDirection:"column",gap:6}}><label style={{fontSize:11,color:C.text2,fontFamily:"'JetBrains Mono',monospace",letterSpacing:".08em"}}>BANKROLL ($)</label><input type="number" value={bankroll} onChange={e=>setBankroll(Number(e.target.value))} style={{background:C.bg3,border:`1px solid ${C.border}`,color:C.text1,borderRadius:4,padding:"6px 10px",fontSize:13,width:120}}/></div>
<div style={{display:"flex",flexDirection:"column",gap:6}}><label style={{fontSize:11,color:C.text2,fontFamily:"'JetBrains Mono',monospace",letterSpacing:".08em"}}>EDGE MINIMO (%)</label><input type="number" value={minEdge} onChange={e=>setMinEdge(Number(e.target.value))} style={{background:C.bg3,border:`1px solid ${C.border}`,color:C.text1,borderRadius:4,padding:"6px 10px",fontSize:13,width:100}}/></div>
<button onClick={runBacktest} disabled={loading} style={{background:loading?C.bg3:C.green,color:loading?C.text2:"#0d1117",border:"none",borderRadius:4,padding:"8px 20px",fontWeight:700,fontSize:13,cursor:loading?"not-allowed":"pointer",fontFamily:"'JetBrains Mono',monospace"}}>{loading?"Analizando...":"EJECUTAR BACKTEST"}</button>
</div>
{error&&<div style={{background:C.redDim,border:`1px solid ${C.red}`,borderRadius:6,padding:14,color:C.red,fontSize:13}}>{error}</div>}
{loading&&<div style={{background:C.bg2,border:`1px solid ${C.border}`,borderRadius:6,padding:30,textAlign:"center",color:C.text2,fontSize:13}}>Descargando datos historicos de {liga}...</div>}
{data&&<><div style={{display:"flex",gap:12,flexWrap:"wrap"}}><StatCard label="Total Apuestas" value={data.total_bets}/><StatCard label="Win Rate" value={`${data.win_rate}%`} color={data.win_rate>40?C.green:data.win_rate>25?C.amber:C.red}/><StatCard label="ROI Kelly" value={`${data.roi_kelly}%`} color={data.roi_kelly>0?C.green:C.red} sub={`Final: $${data.final_bankroll_kelly}`}/><StatCard label="ROI Plana" value={`${data.roi_flat}%`} color={data.roi_flat>0?C.green:C.red} sub={`Final: $${data.final_bankroll_flat}`}/><StatCard label="Mejor Racha" value={`+${data.best_streak}`} color={C.green} sub="ganadas seguidas"/><StatCard label="Peor Racha" value={`-${data.worst_streak}`} color={C.red} sub="perdidas seguidas"/></div>
<div style={{background:C.bg2,border:`1px solid ${C.border}`,borderRadius:6,padding:16}}><div style={{fontSize:11,color:C.text2,fontFamily:"'JetBrains Mono',monospace",letterSpacing:".08em",marginBottom:12}}>ROI ACUMULADO - KELLY vs PLANA</div><ResponsiveContainer width="100%" height={220}><LineChart data={chartData}><XAxis dataKey="n" tick={{fill:C.text2,fontSize:10}}/><YAxis tick={{fill:C.text2,fontSize:10}}/><Tooltip contentStyle={{background:C.bg3,border:`1px solid ${C.border}`,color:C.text1}}/><Legend wrapperStyle={{fontSize:12,color:C.text2}}/><Line type="monotone" dataKey="Kelly" stroke={C.green} dot={false} strokeWidth={2}/><Line type="monotone" dataKey="Plana" stroke={C.blue} dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div>
<div style={{background:C.bg2,border:`1px solid ${C.border}`,borderRadius:6,padding:16}}><div style={{fontSize:11,color:C.text2,fontFamily:"'JetBrains Mono',monospace",letterSpacing:".08em",marginBottom:12}}>TASA DE ACIERTOS POR TIPO</div><ResponsiveContainer width="100%" height={160}><BarChart data={barData}><XAxis dataKey="tipo" tick={{fill:C.text2,fontSize:12}}/><YAxis tick={{fill:C.text2,fontSize:10}} unit="%" domain={[0,100]}/><Tooltip contentStyle={{background:C.bg3,border:`1px solid ${C.border}`,color:C.text1}} formatter={v=>[`${v}%`]}/><Bar dataKey="pct" radius={[4,4,0,0]}>{barData.map((e,i)=><Cell key={i} fill={e.pct>35?C.green:e.pct>20?C.amber:C.red}/>)}</Bar></BarChart></ResponsiveContainer></div></>}
</div>)
}
